config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  namespace :manager do
    mount Sidekiq::Web => "/sidekiq"
    mount Maily::Engine, at: "/maily"

    resources :trips, except: [:edit, :update]
    resources :passengers, only: [:index]
  end

  resources :user_tickets, only: [:index, :destroy]
  resources :wallet, only: [:show, :update]

  get "trips",          to: "trips#index"
  patch "buy_trip/:id", to: "trips#buy_trip", as: "buy_trip"

  # get "wallet",   to: "wallet#show"
  # patch "wallet", to: "wallet#update"

  get "sign_up",   to: "registrations#new"
  post "sign_up",  to: "registrations#create"
  get "profile",   to: "registrations#edit", as: "edit_profile"
  patch "profile", to: "registrations#update"
  delete "delete_account", to: "registrations#destroy"

  get "sign_in",   to: "sessions#new"
  post "sign_in",  to: "sessions#create", as: "log_in"
  delete "logout", to: "sessions#destroy"

  root "trips#index"
end

app/models/trip.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: trips
#
#  id                   :bigint           not null, primary key
#  capacity             :integer
#  departure_time       :datetime
#  price                :decimal(8, 2)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  departure_point_id   :bigint
#  destination_point_id :bigint
#
# Indexes
#
#  index_trips_on_departure_point_id    (departure_point_id)
#  index_trips_on_departure_time        (departure_time)
#  index_trips_on_destination_point_id  (destination_point_id)
#
# Foreign Keys
#
#  fk_rails_...  (departure_point_id => places.id)
#  fk_rails_...  (destination_point_id => places.id)
#
class Trip < ApplicationRecord
  has_many :tickets, dependent: :restrict_with_error
  has_many :users, through: :tickets
  belongs_to :departure_point, class_name: "Place", optional: false
  belongs_to :destination_point, class_name: "Place", optional: false

  validates :capacity, numericality: { only_integer: true, greater_than: 0 }, presence: true
  validates :departure_point, presence: true
  validate  :validates_departure_time
  validates :departure_time, presence: true
  validates :destination_point, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }, presence: true

  # Why this callback is not working? It is because rails verify the tickets relations before this callback is called?
  # before_destroy :cancel_tickets

  scope :today, -> {
                  where("departure_time BETWEEN :start_date AND :end_date",
                    start_date: Time.zone.now.beginning_of_day,
                    end_date: Time.zone.now.end_of_day)
                }

  # validate  :validates_departure_time
  def validates_departure_time
    if departure_time.present? && departure_time < Time.zone.now
      errors.add(:departure_time, "can't be in the past")
    end
  end

  def current_capacity
    capacity - tickets.count
  end

  # def cancel_tickets
  #   tickets.find_each do |ticket|
  #     ticket.refund_user
  #     ticket.destroy
  #   end
  # end

  def current_revenue
    tickets.size * price
  end

  class << self
    def select_by_date(start_date, end_date)
      if start_date.present? && end_date.present?
        where("departure_time BETWEEN :start_date AND :end_date",
          start_date: start_date.beginning_of_day, end_date: end_date.end_of_day).distinct
      elsif start_date.present?
        where("departure_time > :start_date", start_date: start_date.beginning_of_day).distinct
      elsif end_date.present?
        where("departure_time < :end_date", end_date: end_date.end_of_day).distinct
      else
        all
      end
    end
  end
end

app/controllers/manager/trips_controller.rb
# frozen_string_literal: true

module Manager
  class TripsController < ManagerController
    before_action :set_trip, only: [:show, :destroy]

    # GET	/manager/trips
    def index
      start_date = params[:start_date]&.in_time_zone
      end_date = params[:end_date]&.in_time_zone

      @trips =
        Trip.select(:departure_time, :departure_point_id, :destination_point_id, :price, :capacity, :id)
          .includes([:users, :tickets])
          .select_by_date(start_date, end_date)
          .order(departure_time: :asc)
          .page(params[:page])
    end

    # GET	/manager/trips/new
    def new
      @trip = Trip.new
      @places = Place.all.order(name: :asc)
    end

    # POST	/manager/trips
    def create
      @trip = Trip.new(trip_params)

      if @trip.save
        redirect_to(manager_trips_path, notice: t("notice.new", record_type: @trip.model_name.human.downcase))
        logger.info(t("logger.info.new", record_type: @trip.model_name.human, id: @trip.id))
      else
        flash.now[:alert] = t("alert.new", record_type: @trip.model_name.human.downcase)
        logger.error(t("logger.error.new", record_type: @trip.model_name.human))
        render(:new)
      end
    end

    # GET	/manager/trips/:id(
    def show
      @passengers = @trip.users.page(params[:page])
    end

    # DELETE	/manager/trips/:id
    def destroy
      if @trip.departure_time.future?
        success = false
        passengers_id = @trip.users.pluck(:id)
        trip_id = @trip.id

        ActiveRecord::Base.transaction do
          @trip.tickets.find_each do |ticket|
            ticket.refund_user
            ticket.destroy
          end
          success = @trip.destroy
        end

        if success
          TripMailer.cancel_trip_email(passengers_id, trip_id).deliver_later if passengers_id.present?
          redirect_to(manager_trips_path, notice: "Trip cancelled")
        else
          redirect_to(manager_trips_path, alert: "Unable to cancel trip")
        end
      else
        redirect_to(manager_trips_path(params[:page]), alert: "Unable to cancel trip")
      end
    end

    private

    def trip_params
      params.require(:trip).permit(:capacity, :departure_point_id, :departure_time, :destination_point_id, :price)
    end

    def set_trip
      @trip = Trip.find(params[:id])
    end
  end
end

app/controllers/trips_controller.rb
# frozen_string_literal: true

class TripsController < ApplicationController
  # GET /trips
  def index
    start_date = params[:start_date]&.in_time_zone
    end_date = params[:end_date]&.in_time_zone
    date = params[:date]&.in_time_zone

    @trips =
      if start_date.present? || end_date.present?
        Trip.includes([:departure_point, :destination_point])
          .select(:id, :departure_time, :departure_point_id, :destination_point_id, :price)
          .select_by_date(start_date, end_date)
          .order("departure_time ASC")
          .page(params[:page])
      elsif date.present?
        Trip.includes([:departure_point, :destination_point])
          .select(:id, :departure_time, :departure_point_id, :destination_point_id, :price)
          .select_by_date(date, date)
          .order("departure_time ASC")
          .page(params[:page])
      else
        Trip.includes([:departure_point, :destination_point])
          .select(:id, :departure_time, :departure_point_id, :destination_point_id, :price)
          .all
          .order("departure_time ASC")
          .page(params[:page])
      end

    @current_user_trip_ids = current_user.trips.pluck(:id)
  end

  # PATCH /buy_trip
  def buy_trip
    trip = Trip.find(params[:id])

    if current_user.buy_trip(trip)
      logger.info(t("logger.info.bought_trip", user_id: current_user.id, trip_id: trip.id))
      redirect_to(user_tickets_path, notice: t("notice.bought_trip"))
    else
      logger.info(t("logger.error.bought_trip", user_id: current_user.id, trip_id: trip.id))
      redirect_to(trips_path(page: params[:page]), alert: t("alert.bought_trip"))
    end
  end
end

app/helpers/trips_helper.rb
# frozen_string_literal: true

module TripsHelper
end

app/views/trips/index.html.erb
<h1 class="mb-3">Available Trips</h1>

<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <%= form_tag trips_path, method: :get do %>
          <div class="row">
            <div class="col">
              <div class="form-group" style="display: inline-block">
                <%= label_tag(:start_date, "Start Date") %>
                <%= date_field_tag :start_date, params[:start_date], class: "form-control" %>
              </div>
              <div class="form-group" style="display: inline-block">
                <%= label_tag(:end_date, "End Date") %>
                <%= date_field_tag :end_date, params[:end_date], class: "form-control" %>
              </div>
              <div class="form-group"  style="display: inline-block">
                <%= submit_tag "Search", class: "btn btn-primary btn-sm"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <div class="card-body">
        <%= form_tag trips_path, method: :get do %>
          <div class="row">
            <div class="col">
              <div class="form-group" style="display: inline-block">
                <%= label_tag(:date, "Date") %>
                <%= date_field_tag :date, params[:date], class: "form-control" %>
              </div>
              <div class="form-group"  style="display: inline-block">
                <%= submit_tag "Search", class: "btn btn-primary btn-sm"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-sm table-striped table-hover align-middle">
    <thead>
      <tr>
        <th scope="col" >Departure time</th>
        <th scope="col" class="text-center">Departure point</th>
        <th scope="col" class="text-center">Destination</th>
        <th scope="col" class="text-center">Price</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @trips.each do |trip| %>
        <tr>
          <td><%= l(trip.departure_time) %></td>
          <td class="text-center"><%= trip.departure_point.name %></td>
          <td class="text-center"><%= trip.destination_point.name %></td>
          <td class="text-center"><%= number_to_currency(trip.price, :unit => "€") %></td>
          <td>
            <% if !@current_user_trip_ids.include?(trip.id) && trip.departure_time.future? %>
              <%= button_to "Buy", buy_trip_path(trip, page: params[:page]), method: :patch,
                  class: "btn btn-success btn-sm", 
                  data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @trips %>