config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  namespace :manager do
    mount Sidekiq::Web => "/sidekiq"
    mount Maily::Engine, at: "/maily"

    resources :trips, except: [:edit, :update]
    resources :passengers, only: [:index]
  end

  resources :user_tickets, only: [:index, :destroy]
  resources :wallet, only: [:show, :update]

  get "trips",          to: "trips#index"
  patch "buy_trip/:id", to: "trips#buy_trip", as: "buy_trip"

  # get "wallet",   to: "wallet#show"
  # patch "wallet", to: "wallet#update"

  get "sign_up",   to: "registrations#new"
  post "sign_up",  to: "registrations#create"
  get "profile",   to: "registrations#edit", as: "edit_profile"
  patch "profile", to: "registrations#update"
  delete "delete_account", to: "registrations#destroy"

  get "sign_in",   to: "sessions#new"
  post "sign_in",  to: "sessions#create", as: "log_in"
  delete "logout", to: "sessions#destroy"

  root "trips#index"
end

app/controllers/user_tickets_controller.rb
# frozen_string_literal: true

class UserTicketsController < ApplicationController
  # GET /tickets
  def index
    @tickets =
      current_user.tickets
        .includes([trip: [:departure_point, :destination_point]])
        .order("created_at DESC")
        .page(params[:page])
  end

  # DELETE /tickets/1
  def destroy
    ticket = Ticket.find(params[:id])

    success = false
    if ticket.future_trip?
      ActiveRecord::Base.transaction do
        ticket.refund_user
        success = ticket.destroy
      end
    end

    if success
      logger.info(t("logger.info.destroy", record_type: ticket.model_name.human, id: ticket.id))
      redirect_to(user_tickets_path, notice: t("notice.cancel_trip"))
    else
      logger.info(t("error.info.destroy", record_type: ticket.model_name.human, id: ticket.id))
      redirect_to(user_tickets_path, alert: t("alert.cancel_trip"))
    end
  end
end

app/views/user_tickets/index.html.erb
<h1 class="mb-3">My Tickets</h1>

<div class="table-responsive">
  <table class="table table-sm table-striped table-hover align-middle">
    <thead>
      <tr>
        <th scope="col">Departure time</th>
        <th scope="col" class="text-center">Departure point</th>
        <th scope="col" class="text-center">Destination</th>
        <th scope="col" class="text-center">Price</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= l(ticket.trip.departure_time) %></td>
          <td class="text-center"><%= ticket.trip.departure_point.name %></td>
          <td class="text-center"><%= ticket.trip.destination_point.name %></td>
          <td class="text-center"><%= number_to_currency(ticket.trip.price, :unit => "€") %></td>
          <td class="text-center">
            <% if ticket.future_trip? %>
              <%= button_to "Return", user_ticket_path(ticket), method: :delete, data: { confirm: 'Are you sure? The ticket will be refunded' }, class: "btn btn-danger btn-sm"  %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @tickets %>