config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  namespace :manager do
    mount Sidekiq::Web => "/sidekiq"
    mount Maily::Engine, at: "/maily"

    resources :trips, except: [:edit, :update]
    resources :passengers, only: [:index]
  end

  resources :user_tickets, only: [:index, :destroy]
  resources :wallet, only: [:show, :update]

  get "trips",          to: "trips#index"
  patch "buy_trip/:id", to: "trips#buy_trip", as: "buy_trip"

  # get "wallet",   to: "wallet#show"
  # patch "wallet", to: "wallet#update"

  get "sign_up",   to: "registrations#new"
  post "sign_up",  to: "registrations#create"
  get "profile",   to: "registrations#edit", as: "edit_profile"
  patch "profile", to: "registrations#update"
  delete "delete_account", to: "registrations#destroy"

  get "sign_in",   to: "sessions#new"
  post "sign_in",  to: "sessions#create", as: "log_in"
  delete "logout", to: "sessions#destroy"

  root "trips#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IsProject2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="<%= root_path %>">IS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMainContent" aria-controls="navbarMainContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarMainContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to 'Trips', root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'My Tickets', user_tickets_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'My Wallet', wallet_path(current_user.wallet), class: "nav-link" %>
              </li>

              <% if current_user.manager? %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownManagementMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Management
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownManagementMenu">
                    <li><%= link_to "Trips", manager_trips_path, class: "dropdown-item" %></li>
                    <li><%= link_to "Top Passengers", manager_passengers_path(limit: 5), class: "dropdown-item" %></li>
                  </ul>
                </li>
              <% end %>
            </ul>

            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUserMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.formatted_name %>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownUserMenu">
                  <li><%= link_to "Profile", edit_profile_path, class: "dropdown-item" %></li>
                  <li><%= link_to "Sign out", logout_path, class: "dropdown-item", method: :delete %></li>
                </ul>
              </li>
            </ul>

          </div>
        </div>
      </nav>
    <% end %>

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </symbol>
      <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </symbol>
    </svg>

    <% if alert.present? %>
      <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <div>
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        <div>
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    <% end %>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>